version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: simple-blog-mongo-container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  simple-blog-backend:
    image: praveenlichchavi/simple-blog-backend:latest
    container_name: simple-blog-backend-container
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/simple_blog_backend
    links:
      - mongo 

  simple-blog:
    image: praveenlichchavi/simple-blog:latest
    container_name: simple-blog-frontend-container
    depends_on:
      - simple-blog-backend
    ports:
    - "3000:80"    

  nginx:
    image: praveenlichchavi/nginx:latest
    container_name: simple-blog-nginx-container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - simple-blog
      - simple-blog-backend

volumes:
  mongo_data: