version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: simple-blog-mongo-container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  simple-blog-backend:
    build: ./simple-blog-backend
    container_name: simple-blog-backend-container
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    volumes:
      - ./simple-blog-backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/simple_blog_backend
    links:
      - mongo 

  simple-blog:
    build: ./simple-blog
    container_name: simple-blog-frontend-container
    depends_on:
      - simple-blog-backend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    volumes:
      - ./simple-blog:/app
      - /app/node_modules

volumes:
  mongo_data:
